services:

  db:
    image: postgres:16
    container_name: project-management-system-db
    environment:
      POSTGRES_DB: project-management
      POSTGRES_USER: root
      POSTGRESS_PASSWORD: root
    ports:
      -"5432:5432"
    volumes:
      -pm-data:/var/lib/postgresql/data

  db-ui:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=caicedo.paa@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      -db-ui-data:/var/lib.pgadmin
    ports:
      -"8085:8085"

  api:
    build: .
    container_name: project-management-system
    ports:
      - "8000:8000"
    volumes:
      - .:/app
        # Hay 2 tipos de volumnes:
        # montura: local (a una nueva carpeta en el proyecto 'app-data')
        # manejado por docker (el que usamos aqui)
    restart: unless-stopped # si pasa algo, el contenedor se va a restart
 
